"use client";
import { useState, useEffect } from 'react';

interface StudentWin {
  name: string;
  achievement: string;
  amount: string;
  timeframe: string;
  skill: string;
  country: string;
  image?: string;
}

interface Testimonial {
  name: string;
  role: string;
  content: string;
  rating: number;
  achievement?: string;
}

export default function SocialProofSection() {
  const [currentTestimonial, setCurrentTestimonial] = useState(0);
  const [studentCount, setStudentCount] = useState(0);
  const [revenueGenerated, setRevenueGenerated] = useState(0);

  const studentWins: StudentWin[] = [
    {
      name: "Sarah M.",
      achievement: "First MRR Sale",
      amount: "$499",
      timeframe: "3 days",
      skill: "UBC Reseller",
      country: "🇺🇸 USA"
    },
    {
      name: "Mike R.",
      achievement: "Monthly Revenue",
      amount: "$2,495",
      timeframe: "1 month",
      skill: "UBC + Branding",
      country: "🇬🇧 UK"
    },
    {
      name: "Elena V.",
      achievement: "Course Sales",
      amount: "$4,990",
      timeframe: "6 weeks",
      skill: "MRR Business",
      country: "�� Spain"
    },
    {
      name: "David K.",
      achievement: "Launch Revenue",
      amount: "$1,497",
      timeframe: "2 weeks",
      skill: "Digital Marketing",
      country: "�� Australia"
    },
    {
      name: "Maria S.",
      achievement: "Reseller Income",
      amount: "$3,493",
      timeframe: "1 month",
      skill: "Course Reselling",
      country: "🇨🇦 Canada"
    },
    {
      name: "James L.",
      achievement: "MRR Profits",
      amount: "$5,988",
      timeframe: "8 weeks",
      skill: "UBC Business",
      country: "�� Germany"
    }
  ];

  const testimonials: Testimonial[] = [
    {
      name: "Jennifer Lopez",
      role: "UBC Student & Reseller",
      content: "I bought the Ultimate Branding Course and made my investment back in just 5 days! The Master Resell Rights are incredible - I'm earning $499 per sale.",
      rating: 5,
      achievement: "ROI in 5 days"
    },
    {
      name: "Mark Thompson",
      role: "Digital Entrepreneur",
      content: "The course content is top-notch and the MRR model is brilliant. I've been selling this course for 3 months and it's become my main income source.",
      rating: 5,
      achievement: "Main income source"
    },
    {
      name: "Sophie Chen",
      role: "Online Marketer",
      content: "Best investment I've made this year. The course teaches real branding skills AND I can resell it. It's like having a business in a box!",
      rating: 5,
      achievement: "Business in a box"
    }
  ];

  // Animated counters - Using conservative, realistic numbers
  useEffect(() => {
    const studentTarget = 2500; // More realistic number for UBC
    const revenueTarget = 1250000; // $1.25M generated by students (conservative estimate)
    
    const animateCounter = (target: number, setter: (value: number) => void, duration: number = 2000) => {
      const start = Date.now();
      const animate = () => {
        const elapsed = Date.now() - start;
        const progress = Math.min(elapsed / duration, 1);
        const easeOut = 1 - Math.pow(1 - progress, 3);
        setter(Math.floor(target * easeOut));
        
        if (progress < 1) {
          requestAnimationFrame(animate);
        }
      };
      animate();
    };

    animateCounter(studentTarget, setStudentCount);
    animateCounter(revenueTarget, setRevenueGenerated);
  }, []);

  // Auto-rotate testimonials
  useEffect(() => {
    const interval = setInterval(() => {
      setCurrentTestimonial((prev) => (prev + 1) % testimonials.length);
    }, 5000);
    return () => clearInterval(interval);
  }, [testimonials.length]);

  const formatMoney = (num: number) => {
    if (num >= 1000000000) return `$${(num / 1000000000).toFixed(1)}B`;
    if (num >= 1000000) return `$${(num / 1000000).toFixed(0)}M`;
    if (num >= 1000) return `${(num / 1000).toFixed(0)}K`;
    return num.toString();
  };

  return (
    <section className="section-padding relative overflow-hidden bg-black/20">
      {/* Background */}
      <div className="absolute inset-0 bg-gradient-to-r from-accent/5 via-transparent to-accent/5" />
      
      <div className="container relative z-10">
        {/* Header */}
        <div className="text-center mb-16 animate-slide-up">
          <div className="inline-block glass-strong px-6 py-3 rounded-full mb-6">
            <span className="text-accent font-semibold text-sm uppercase tracking-wider">
              🏆 STUDENT SUCCESS
            </span>
          </div>
          <h2 className="text-4xl md:text-6xl font-heading font-black mb-6">
            <span className="text-gradient">REAL STUDENTS</span><br />
            <span className="text-white">REAL RESULTS</span>
          </h2>
        </div>

        {/* Stats */}
        <div className="grid md:grid-cols-3 gap-8 mb-16">
          <div className="glass-card p-8 text-center rounded-xl animate-scale-in">
            <div className="text-4xl md:text-6xl font-black text-gradient mb-2">
              {studentCount.toLocaleString()}+
            </div>
            <div className="text-lg font-semibold text-white mb-2">Students</div>
            <div className="text-sm text-secondary">Learning & earning</div>
          </div>
          
          <div className="glass-card p-8 text-center rounded-xl animate-scale-in delay-200">
            <div className="text-4xl md:text-6xl font-black text-gradient mb-2">
              {formatMoney(revenueGenerated)}+
            </div>
            <div className="text-lg font-semibold text-white mb-2">Generated</div>
            <div className="text-sm text-secondary">By our students</div>
          </div>
          
          <div className="glass-card p-8 text-center rounded-xl animate-scale-in delay-400">
            <div className="text-4xl md:text-6xl font-black text-gradient mb-2">
              419+
            </div>
            <div className="text-lg font-semibold text-white mb-2">Video Lessons</div>
            <div className="text-sm text-secondary">37+ hours content</div>
          </div>
        </div>

        {/* Student Wins */}
        <div className="mb-16">
          <h3 className="text-3xl font-bold text-center mb-8 text-gradient">Latest Student Wins</h3>
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
            {studentWins.map((win, index) => (
              <div 
                key={index}
                className={`glass-card p-6 rounded-xl animate-slide-up delay-${index * 100} hover:scale-105 transition-transform`}
              >
                <div className="flex items-center justify-between mb-4">
                  <div>
                    <div className="font-bold text-white">{win.name}</div>
                    <div className="text-sm text-secondary">{win.country}</div>
                  </div>
                  <div className="glass-strong px-3 py-1 rounded-full">
                    <span className="text-accent text-xs font-bold">{win.skill}</span>
                  </div>
                </div>
                
                <div className="mb-3">
                  <div className="text-2xl font-black text-accent">{win.amount}</div>
                  <div className="text-sm text-gray-300">{win.achievement}</div>
                </div>
                
                <div className="text-xs text-secondary">
                  🕐 {win.timeframe}
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Testimonials */}
        <div className="mb-16">
          <h3 className="text-3xl font-bold text-center mb-8 text-gradient">What Students Say</h3>
          <div className="max-w-4xl mx-auto">
            <div className="glass-strong p-8 rounded-2xl relative overflow-hidden">
              {/* Testimonial content */}
              <div className="text-center">
                <div className="flex justify-center mb-4">
                  {[...Array(5)].map((_, i) => (
                    <svg key={i} className="w-6 h-6 text-yellow-400" fill="currentColor" viewBox="0 0 20 20">
                      <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
                    </svg>
                  ))}
                </div>
                
                <blockquote className="text-xl text-gray-200 mb-6 italic">
                  "{testimonials[currentTestimonial].content}"
                </blockquote>
                
                <div className="flex items-center justify-center space-x-4">
                  <div>
                    <div className="font-bold text-white">{testimonials[currentTestimonial].name}</div>
                    <div className="text-sm text-secondary">{testimonials[currentTestimonial].role}</div>
                  </div>
                  {testimonials[currentTestimonial].achievement && (
                    <div className="glass px-4 py-2 rounded-full">
                      <span className="text-accent font-semibold text-sm">
                        {testimonials[currentTestimonial].achievement}
                      </span>
                    </div>
                  )}
                </div>
              </div>

              {/* Navigation dots */}
              <div className="flex justify-center mt-6 space-x-2">
                {testimonials.map((_, index) => (
                  <button
                    key={index}
                    onClick={() => setCurrentTestimonial(index)}
                    className={`w-3 h-3 rounded-full transition-colors ${
                      currentTestimonial === index ? 'bg-accent' : 'bg-gray-600'
                    }`}
                  />
                ))}
              </div>
            </div>
          </div>
        </div>

        {/* Community feed simulation */}
        <div className="text-center">
          <h3 className="text-2xl font-bold mb-8 text-gradient">Join The UBC Community</h3>
          <div className="glass-card p-8 rounded-xl max-w-2xl mx-auto">
            <div className="flex items-center justify-center space-x-8 mb-6">
              <div className="text-center">
                <div className="text-2xl font-bold text-accent">500+</div>
                <div className="text-sm text-secondary">Active Members</div>
              </div>
              <div className="text-center">
                <div className="text-2xl font-bold text-accent">24/7</div>
                <div className="text-sm text-secondary">Support</div>
              </div>
              <div className="text-center">
                <div className="text-2xl font-bold text-accent">$499</div>
                <div className="text-sm text-secondary">Fixed Price</div>
              </div>
            </div>
            <p className="text-gray-300 mb-6">
              Connect with successful UBC resellers worldwide. Share sales wins, 
              get marketing tips, and grow your MRR business together.
            </p>
            <div className="glass px-6 py-3 rounded-full inline-block">
              <span className="text-accent font-semibold">💬 Private Community Access</span>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
