packages:
  - .
  - packages/*

ignoredBuiltDependencies:
  - '@prisma/engines'
  - ngrok

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@tailwindcss/oxide'
  - prisma
  - sharp
