name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # === required secrets (set in GitHub → Settings → Secrets and variables → Actions) ===
      ADMIN_SECRET: ${{ secrets.ADMIN_SECRET }}
      RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
      EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      NEXT_PUBLIC_SITE_URL: ${{ secrets.NEXT_PUBLIC_SITE_URL }}
      # Optional (set only if you use them)
      NEXT_PUBLIC_TEST_EMAIL: ${{ secrets.NEXT_PUBLIC_TEST_EMAIL }}
      TEST_EMAIL: ${{ secrets.TEST_EMAIL }}
      DUMMY_PAYMENT_MODE: ${{ secrets.DUMMY_PAYMENT_MODE }}

    steps:
      - uses: actions/checkout@v4

      # Make pnpm available first so setup-node can cache it
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.12.2
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cach
