name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      ADMIN_SECRET: ${{ secrets.ADMIN_SECRET }}
      # add other secrets here if needed

    steps:
      - uses: actions/checkout@v4

      # 1) Install pnpm BEFORE setup-node’s cache step
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.12.2
          run_install: false

      # 2) Now setup-node can safely use cache: 'pnpm'
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Show versions
        run: |
          node -v
          pnpm -v

      - name: Cache Turbo
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Install dependencies (frozen)
        run: pnpm install --frozen-lockfile

      - name: Generate Prisma Client
        run: pnpm db:generate

      - name: Lint, test, build
        run: pnpm turbo run lint test build --filter=!packages/ui --filter=!packages/server

      - name: Start app
        run: |
          pnpm start & \
          npx wait-on http://localhost:3000

      - name: Lighthouse budget check
        run: pnpm lighthouse-ci http://localhost:3000 --budget-path=.lighthousebudget.json
